server:
  port: 8081
spring:
  application:
    name: student
  cloud:
    config:
      uri: optional:configserver:http://configserver:8088/
      fail-fast: true  # Fail startup if cannot connect to config server
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
        max-attempts: 20
  profiles:
    active: prod
